### ISSUE TITLE
Parse errors are printed with escape codes

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/update-nix-fetchgit#4]
`default.nix`:

``` nix
let
```

```
$ update-nix-fetchgit default.nix
"\ESC[1m/tmp/fetchtest/default.nix\ESC[0m:\ESC[1m2\ESC[0m:\ESC[1m1\ESC[0m: \ESC[91merror\ESC[0m: unexpected\n    EOF, expected: \"in\",\n    inherited binding,\n    variable binding\n\ESC[1m\ESC[94m<EOF>\ESC[0;1m\ESC[0m \n\ESC[92m^\ESC[0m     "
```

**Comment by DavidEGrayson** [comment]
Hmmm.  Weird, it prints properly if I modify `printErrorAndExit` in Main.hs like this:

``` haskell
printErrorAndExit :: Warning -> IO ()
printErrorAndExit e = do
  print x
  exitWith (ExitFailure 1)
  where (CouldNotParseInput x) = e
```

**Comment by DavidEGrayson** [comment]
OK, I get it now.  `print (show x)` prints the wrong thing, while `print x` prints the right thing.  That's because `(show x)` is a string, and when you apply `show` to a string it converts it into something that is a valid Haskell expression.  But that's now what we want, we want a printing function that will actually just print the string we give to it.
